baseURL = 'https://blaher.me/patinaartscentre/'
languageCode = 'en-us'
title = 'Patina Arts Centre'

[[menus.main]]
name = 'Home'
pageRef = 'https://blaher.me/patinaartscentre/'
weight = 10

[[menus.main]]
name = 'Exhibitions'
pageRef = 'https://blaher.me/patinaartscentre/exhibits'
weight = 20

[[menus.main]]
name = 'Artist Opportunities'
pageRef = 'https://blaher.me/patinaartscentre/opportunities'
weight = 30

[[menus.main]]
name = 'Comedy'
pageRef = 'https://blaher.me/patinaartscentre/comedy'
weight = 40

[[menus.main]]
name = 'Classes & Workshops'
pageRef = 'https://blaher.me/patinaartscentre/classes'
weight = 50

[[menus.main]]
name = 'Resident Artists'
pageRef = 'https://blaher.me/patinaartscentre/artists'
weight = 60

[[menus.main]]
name = 'About PAC'
pageRef = 'https://blaher.me/patinaartscentre/about'
weight = 70

[[menus.main]]
name = 'Contact'
pageRef = 'https://blaher.me/patinaartscentre/contact'
weight = 80

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
